### ISSUE TITLE
Discern internal modules for the disovery feature

### ISSUE THREAD

**Issue by nikita-volkov** [tfausak/cabal-gild#64] opened 2024-04-20 10:16 UTC
# Problem

The automatic module discovery feature is great, but it does not address the issue of discerning the private vs public modules.

I've found [a workaround](https://github.com/nikita-volkov/hasql-pool/blob/8a9389f22b08f7eff7443c2744cc1ff2320aa770/hasql-pool.cabal#L71-L82) for this, but it's highly uncommon, hence frustrating, and it complicates navigation.

# Suggestions

## Marker in the module header

Treat a special marker comment in the headers of Haskell modules as a sign to treat it as an internal module. E.g.:

```haskell
{- cabal-gild: internal -}
{-# LANGUAGE SomeHaskellExtension #-}
module ModuleName where
```

## Specially treated namespace

If a module namespace contains some trigger word, consider it internal. E.g., if the trigger word is `Internal` then the following modules will be put under the `other-modules` section:

- `Data.Text.Internal`
- `Data.Text.Internal.Builder`

I guess this one should be easier to implement.

**Comment by tfausak** [comment] 2024-04-21 13:17
I think this is similar to #59.

**Comment by tfausak** [comment] 2024-04-21 19:24
I'm going to close this as a duplicate of #59. They're not exactly the same, but I think a solution to that issue should solve your issue here as well.

**Closed as completed by tfausak** 2024-04-21 19:24 UTC
Labels: duplicate, enhancement
